name 'sainsburys'
maintainer 'Luke Bradbury'
maintainer_email 'luke.dolman@gmail.com'
license 'Apache 2.0'
description 'Installs/Configures sainsburys demo go app'
long_description 'Installs/Configures sainsburys demo go app'
version '0.1.0'

depends 'golang'
depends 'nginx'
